# Generated by Django 3.2 on 2023-02-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahha_service', '0004_auto_20230206_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='gps_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='gps_latitude',
            field=models.FloatField(null=True),
        ),
    ]
