# Generated by Django 3.2 on 2023-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahha_service', '0006_timeslot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='gps_latitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='gps_longitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='periodicity',
            field=models.CharField(choices=[('Jour', 'Jour'), ('Semaine', 'Semaine')], default='Semaine', max_length=120),
        ),
    ]
