# Generated by Django 3.2 on 2023-02-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sahha_service', '0007_auto_20230212_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
