# Generated by Django 3.2 on 2023-02-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahha_service', '0008_alter_timeslot_time_slot_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='time_slot_owner',
        ),
    ]
