# Generated by Django 3.2 on 2023-04-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahha_service', '0010_timeslot_time_slot_intervenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahhauser',
            name='agence_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence', to='sahha_service.agence'),
        ),
    ]
