class GENERAL:
    PAGE_SIZE = 5
    DATETIME_FORMAT = "%d/%m/%Y %H:%M:%S"
    DATE_FORMAT = "%d/%m/%Y"
    FROM_EMAIL = 'Do not Reply <do_not_reply@gmail.com>'


class STATUS:
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    ERROR = "ERROR"


class ROLE:
    ADMIN = "ADMIN"
    ORGANIZER = "ORGANIZER"
    OPTIONS = (ADMIN, ORGANIZER, )

class ERRORS:
    INTERNAL_ERROR = 0
    INVALID_DATA = 1
    UN_AUTHORIZED = 2
    MISSING_DATA = 3
    DOESNT_EXIST = 4
    CREATE_ERROR = 5
    UPDATE_ERROR = 6
    UPDATE_CREATE_ERROR = 7
    DELETE_ERROR = 8
    ALREADY_EXISTS = 9
    ACCOUNT_INACTIVE = 10
    ACCOUNT_SUSPENDED = 11
    SENDING_ERROR = 12
    PHONE_NOT_VERIFIED = 13
    INVALID_OAUTH_TOKEN = 14
    ACCOUNT_NOT_SUBSCRIBED = 15
    INVALID_TOKEN = 16
    INVALID_SYSTEM_DATA = 17
    NOT_EQUAL = 18
    PASSWORD_NOT_COMPLEX = 19
    COMMON_EXCEPTION = 20